
version: "2.4"

services:
  ## https://github.com/willfarrell/docker-autoheal
  autoheal:
    image: willfarrell/autoheal:1.1.0
    restart: always
    network_mode: none
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ## https://containrrr.github.io/watchtower
  watchtower:
    image: containrrr/watchtower
    restart: always
    network_mode: bridge
    hostname: ${WATCHTOWER_HOSTNAME}
    environment:
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${WATCHTOWER_NOTIFICATION_EMAIL}
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ${WATCHTOWER_NOTIFICATION_EMAIL}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ${WATCHTOWER_NOTIFICATION_EMAIL}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${WATCHTOWER_MAIL_PASSWORD}
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --no-color --schedule "${WATCHTOWER_SCHEDULE}"
