version: '2.4'

networks:
  frontend:
    name: ingressnet
## Independant services use:
# networks:
#   frontend:
#     external: true
#     name: ingressnet

volumes:
  vhost:
  rphtml:
  acme:

services:
  rp:
    image: nginxproxy/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
      - ./certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - rphtml:/usr/share/nginx/html
    cpu_shares: 2048
    networks:
      - frontend

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    restart: always
    network_mode: bridge
    environment:
      DEFAULT_EMAIL: <Redacted>
    volumes_from: 
      - rp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
